repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      exclude: ^tmp/
      language_version: python3.9
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      exclude: ^tmp/
      args: ['--max-line-length=88', '--extend-ignore=E203']
